export type ExchangeId = 'binance' | 'bybit' | 'okx' | 'gate' | 'mexc' | 'bitget' | 'kucoin' | 'htx' | 'crypto.com' | 'coinbase';
export type DiscoveryStatus = 'AVAILABLE' | 'UNAVAILABLE' | 'RATE_LIMITED' | 'ERROR' | 'EMPTY_RESULT';
export type SourceHealth = { status: DiscoveryStatus; endpoint: string; error?: string; httpStatus?: number };
export type NormalizedSpotMarket = {
  exchange: ExchangeId;
  exchangeSymbol: string;
  baseAsset: string;
  quoteAsset: string;
  canonicalAssetId: string;
  canonicalPair: string;
  marketType: 'spot';
  status: string;
  pricePrecision?: number;
  quantityPrecision?: number;
  tickSize?: number;
  lotSize?: number;
  minimumQuantity?: number;
  minimumNotional?: number;
  volumeBase24h?: number;
  volumeQuote24h?: number;
  turnover24h?: number;
  lastPrice?: number;
  exchangeTimestamp?: number;
  assetMapping: 'exact-symbol' | 'known-alias' | 'ambiguous';
};
export type ExchangeDiscoveryResult = {
  exchange: ExchangeId;
  status: DiscoveryStatus;
  discoveredAt: number;
  marketCount: number;
  markets: NormalizedSpotMarket[];
  marketSource: SourceHealth;
  tickerSource?: SourceHealth;
  warnings: string[];
  durationMs: number;
};
export type DiscoveryConfig = {
  target: number;
  minExchangeCount: number;
  supportedExchanges: ExchangeId[];
  majorQuoteAssets: string[];
  meaningfulVolumeMinimum: number;
  scoreWeights: { coverage: number; liquidity: number; liquidExchanges: number; quoteAvailability: number; activity: number };
};
export type RankedAsset = {
  rank: number;
  assetId: string;
  symbol: string;
  name?: string;
  isStablecoin: false;
  isQuoteAsset: boolean;
  exchangeCount: number;
  exchanges: ExchangeId[];
  eligiblePairCount: number;
  liquidExchangeCount: number;
  totalVolume24h: number | null;
  totalVolume24hByQuoteAsset: Record<string, number>;
  medianVolume24h: number | null;
  liquidityScore: number | null;
  arbitrageRelevanceScore: number;
  scoreComponents: Record<string, number | null>;
  scoreMissingComponents: string[];
  status: 'ELIGIBLE' | 'PARTIAL_DISCOVERY';
  selectionReason: string;
};
export type EligiblePair = {
  canonicalPair: string;
  baseAsset: string;
  quoteAsset: string;
  exchangeCount: number;
  exchanges: ExchangeId[];
  markets: NormalizedSpotMarket[];
  status: 'ELIGIBLE' | 'PARTIAL_DISCOVERY';
};
export type DiscoveryReport = {
  schemaVersion: 1;
  runId: string;
  startedAt: number;
  completedAt: number;
  status: 'COMPLETE' | 'PARTIAL' | 'FAILED';
  config: DiscoveryConfig;
  exchanges: ExchangeDiscoveryResult[];
  marketsDiscovered: number;
  uniqueCanonicalAssetsDiscovered: number;
  nonStableAssetsEligible: number;
  selectedAssetCount: number;
  quoteAssets: Array<{ symbol: string; isStablecoin: boolean; isMajorQuote: boolean }>;
  assets: RankedAsset[];
  eligiblePairs: EligiblePair[];
  pairCount: number;
  coverageComplete: boolean;
  methodology: {
    scoring: string;
    missingData: string;
    volumeAggregation: string;
    stablecoinClassification: string;
    marketLiquidityDisclaimer: string;
  };
};
