import { describe,expect,it } from 'vitest';
import { evaluateBothDirections, type MarketInput } from './arbitrage';
import { feeSchedules } from './fees';
import { createBook } from './orderbook';
const now=1_700_000_000_000;
const market=(exchange:string,bids:{price:number;quantity:number}[],asks:{price:number;quantity:number}[],status='LIVE'):MarketInput=>({book:createBook(exchange,'BTC/USDT',bids,asks,10,now,now),connectionStatus:status,sequenceValid:status==='LIVE'});
describe('depth-aware cross-exchange arbitrage',()=>{
 it('rejects same exchange',()=>{const x=market('binance',[{price:102,quantity:1}],[{price:101,quantity:1}]);expect(evaluateBothDirections(x,x,feeSchedules,.1,now).aToB.status).toBe('REJECTED_INVALID_BOOK');});
 it('evaluates both directions with a common quantity, depth, fees and slippage',()=>{const binance=market('binance',[{price:99,quantity:2}],[{price:100,quantity:.4},{price:101,quantity:.6}]),bybit=market('bybit',[{price:103,quantity:.3},{price:102,quantity:.7}],[{price:104,quantity:2}]);const result=evaluateBothDirections(binance,bybit,feeSchedules,1,now);const forward=result.aToB.opportunity;expect(forward?.executableQuantity).toBe(1);expect(forward?.averageBuyPrice).toBeCloseTo(100.6);expect(forward?.averageSellPrice).toBeCloseTo(102.3);expect(forward?.buyFeeRate).toBe(.001);expect(forward?.sellFeeRate).toBe(.001);expect(forward?.estimatedSlippage).toBeGreaterThan(0);expect(forward?.estimatedNetProfit).toBeLessThan(forward?.grossSpread??0);expect(forward?.status).toBe('OPPORTUNITY');expect(result.bToA.status).toBe('NO_OPPORTUNITY');});
 it('rejects stale, resyncing, invalid and insufficient books',()=>{const a=market('binance',[{price:100,quantity:1}],[{price:101,quantity:1}]),fresh=market('bybit',[{price:103,quantity:1}],[{price:104,quantity:1}]);expect(evaluateBothDirections({...a,book:{...a.book!,exchangeTimestamp:now-3000}},fresh,feeSchedules,.1,now).aToB.status).toBe('REJECTED_STALE_DATA');expect(evaluateBothDirections(a,{...fresh,connectionStatus:'RESYNCING',sequenceValid:false},feeSchedules,.1,now).aToB.status).toBe('EXCHANGE_RESYNCING');expect(evaluateBothDirections(a,market('bybit',[{price:105,quantity:1}],[{price:104,quantity:1}]),feeSchedules,.1,now).aToB.status).toBe('REJECTED_INVALID_BOOK');expect(evaluateBothDirections(a,fresh,feeSchedules,2,now).aToB.status).toBe('REJECTED_INSUFFICIENT_LIQUIDITY');});
 it('does not return a valid opportunity when fees erase edge',()=>{const a=market('binance',[{price:99.8,quantity:1}],[{price:100,quantity:1}]),b=market('bybit',[{price:100.1,quantity:1}],[{price:100.2,quantity:1}]);expect(evaluateBothDirections(a,b,feeSchedules,.1,now).aToB.status).toBe('NO_OPPORTUNITY');});
});
