import type { NormalizedOrderBook, OrderBookLevel } from './types';
import type { ExchangeFeeSchedule } from './fees';

export type EvaluationStatus='OPPORTUNITY'|'NO_OPPORTUNITY'|'REJECTED_STALE_DATA'|'REJECTED_INVALID_BOOK'|'REJECTED_INSUFFICIENT_LIQUIDITY'|'EXCHANGE_DISCONNECTED'|'EXCHANGE_RESYNCING';
export type Opportunity={symbol:string;buyExchange:string;sellExchange:string;referenceQuantity:number;executableQuantity:number;executableNotional:number;bestBuyAsk:number;bestSellBid:number;averageBuyPrice:number;averageSellPrice:number;grossSpread:number;grossSpreadPercent:number;buyFeeRate:number;sellFeeRate:number;buyFees:number;sellFees:number;buyFeeCurrency:string;sellFeeCurrency:string;estimatedSlippage:number;estimatedNetSpreadPercent:number;estimatedNetProfit:number;timestamp:number;buyExchangeTimestamp:number|null;sellExchangeTimestamp:number|null;buyDataAgeMs:number|null;sellDataAgeMs:number|null;status:EvaluationStatus;valid:boolean;rejectionReason:string|null;};
export type MarketInput={book:NormalizedOrderBook|null;connectionStatus:string;sequenceValid:boolean;};
export type FeeMap=Record<string,ExchangeFeeSchedule>;
export type Evaluation={status:EvaluationStatus;opportunity:Opportunity|null;reason:string|null};
export function walkLevels(levels:OrderBookLevel[],quantity:number){let remaining=quantity,filled=0,notional=0;for(const l of levels){if(remaining<=1e-12)break;if(!Number.isFinite(l.price)||l.price<=0||!Number.isFinite(l.quantity)||l.quantity<=0)continue;const take=Math.min(remaining,l.quantity);filled+=take;notional+=take*l.price;remaining-=take;}return {quantity:filled,notional,averagePrice:filled?notional/filled:0,complete:remaining<=Math.max(1e-12,quantity*1e-9)};}
export function evaluateDirection(buy:MarketInput,sell:MarketInput,buyFee:ExchangeFeeSchedule,sellFee:ExchangeFeeSchedule,referenceQuantity:number,now=Date.now(),maxAgeMs=2000):Evaluation{
 const reject=(status:EvaluationStatus,reason:string):Evaluation=>({status,opportunity:null,reason});
 if(!buy.book||!sell.book||['DISCONNECTED','ERROR'].includes(buy.connectionStatus)||['DISCONNECTED','ERROR'].includes(sell.connectionStatus))return reject('EXCHANGE_DISCONNECTED','One or both exchange feeds are disconnected.');
 if(['RESYNCING','SYNCING','STARTING','CONNECTED'].includes(buy.connectionStatus)||['RESYNCING','SYNCING','STARTING','CONNECTED'].includes(sell.connectionStatus)||!buy.sequenceValid||!sell.sequenceValid)return reject('EXCHANGE_RESYNCING','One or both order books are not synchronized with valid sequence state.');
 const b=buy.book,s=sell.book,ba=bookAge(b,now),sa=bookAge(s,now);if(ba===null||sa===null||ba<0||sa<0||ba>maxAgeMs||sa>maxAgeMs)return reject('REJECTED_STALE_DATA','One or both books have missing, invalid, or stale timestamps.');
 if(!validBook(b)||!validBook(s))return reject('REJECTED_INVALID_BOOK','A book has missing levels, invalid quantities/prices, or crossed best prices.');
 if(b.exchange===s.exchange)return reject('REJECTED_INVALID_BOOK','Buy and sell exchanges must differ.');
 if(!(referenceQuantity>0))return reject('REJECTED_INSUFFICIENT_LIQUIDITY','Reference quantity must be positive.');
 const buyWalk=walkLevels(b.asks,referenceQuantity),sellWalk=walkLevels(s.bids,referenceQuantity);if(!buyWalk.complete||!sellWalk.complete)return reject('REJECTED_INSUFFICIENT_LIQUIDITY','The configured reference BTC quantity cannot be fully executed on both books.');const qty=referenceQuantity;
 const buyExec=buyWalk,sellExec=sellWalk;
 const buyFees=feeCost(buyFee,buyExec.notional,qty,buyExec.averagePrice),sellFees=feeCost(sellFee,sellExec.notional,qty,sellExec.averagePrice),grossProfit=sellExec.notional-buyExec.notional,grossPercent=grossProfit/buyExec.notional,netProfit=grossProfit-buyFees.quoteCost-sellFees.quoteCost,netPercent=netProfit/buyExec.notional,topBuy=b.asks[0].price,topSell=s.bids[0].price,topGrossPercent=(topSell-topBuy)/topBuy,slippage=topGrossPercent-grossPercent;
 const opportunity:Opportunity={symbol:b.symbol,buyExchange:b.exchange,sellExchange:s.exchange,referenceQuantity,executableQuantity:qty,executableNotional:buyExec.notional,bestBuyAsk:topBuy,bestSellBid:topSell,averageBuyPrice:buyExec.averagePrice,averageSellPrice:sellExec.averagePrice,grossSpread:grossProfit,grossSpreadPercent:grossPercent,buyFeeRate:buyFee.takerFee,sellFeeRate:sellFee.takerFee,buyFees:buyFees.raw,sellFees:sellFees.raw,buyFeeCurrency:buyFee.feeCurrencyAssumption,sellFeeCurrency:sellFee.feeCurrencyAssumption,estimatedSlippage:slippage,estimatedNetSpreadPercent:netPercent,estimatedNetProfit:netProfit,timestamp:now,buyExchangeTimestamp:b.exchangeTimestamp,sellExchangeTimestamp:s.exchangeTimestamp,buyDataAgeMs:ba,sellDataAgeMs:sa,status:netProfit>0?'OPPORTUNITY':'NO_OPPORTUNITY',valid:netProfit>0,rejectionReason:netProfit>0?null:'Fees and execution impact leave no positive estimated net return.'};
 return {status:opportunity.status,opportunity,reason:opportunity.rejectionReason};
}
export function evaluateBothDirections(a:MarketInput,b:MarketInput,fees:FeeMap,referenceQuantity:number,now=Date.now(),maxAgeMs=2000){const fa=fees[a.book?.exchange??''],fb=fees[b.book?.exchange??''];if(!fa||!fb){const x:Evaluation={status:'REJECTED_INVALID_BOOK',opportunity:null,reason:'Fee schedule unavailable for one or both exchanges.'};return {aToB:x,bToA:x};}return {aToB:evaluateDirection(a,b,fa,fb,referenceQuantity,now,maxAgeMs),bToA:evaluateDirection(b,a,fb,fa,referenceQuantity,now,maxAgeMs)};}
function validBook(b:NormalizedOrderBook){if(!b.bids.length||!b.asks.length)return false;const levels=[...b.bids,...b.asks];if(levels.some(x=>!Number.isFinite(x.price)||x.price<=0||!Number.isFinite(x.quantity)||x.quantity<=0))return false;return b.bids[0].price<b.asks[0].price;}
function bookAge(b:NormalizedOrderBook,now:number){return b.exchangeTimestamp===null?null:now-b.exchangeTimestamp;}
function feeCost(fee:ExchangeFeeSchedule,notional:number,quantity:number,averagePrice:number){const raw=(fee.feeCurrencyAssumption==='BASE'?quantity*fee.takerFee:notional*fee.takerFee);return {raw,quoteCost:fee.feeCurrencyAssumption==='BASE'?raw*averagePrice:raw};}
