import WebSocket from 'ws';
import type { ConnectionDiagnostics, ExchangeAdapter, NormalizedOrderBook, OrderBookLevel, AdapterStatus } from './types';
import { LocalOrderBook } from './orderbook';
export type AdapterState=AdapterStatus;
export type ConnectionDiagnostic=ConnectionDiagnostics;

export class BinanceAdapter implements ExchangeAdapter {
 private ws?:WebSocket; private timer?:NodeJS.Timeout; private stopped=false; private reconnects=0; private buffered:any[]=[]; private book:LocalOrderBook; private state:AdapterState='STARTING'; private firstMessageLogged=false;
 private diagnostic:ConnectionDiagnostic={error:null,closeCode:null,closeReason:null,reconnectAttempt:0,lastEvent:null};
 readonly exchange='binance'; readonly symbol:string;
 constructor(private streamSymbol='btcusdt',private onUpdate:(x:BinanceAdapter)=>void=()=>{}){this.symbol='BTC/USDT';this.book=new LocalOrderBook(this.exchange,this.symbol);}
 start(){this.stopped=false;this.connect();}
 private log(message:string){this.diagnostic.lastEvent=message;console.log(message);this.onUpdate(this);}
 private fail(error:unknown){const message=error instanceof Error?error.message:String(error);this.diagnostic.error=message;this.state='ERROR';console.error(`Binance WebSocket: ERROR\nError: ${message}\nClose code: ${this.diagnostic.closeCode??'—'}\nClose reason: ${this.diagnostic.closeReason||'—'}\nReconnect attempt: ${this.reconnects+1}`);this.onUpdate(this);}
 private connect(){if(this.stopped||this.ws)return;this.firstMessageLogged=false;this.buffered=[];this.state='STARTING';this.book.markResyncing();this.diagnostic={...this.diagnostic,closeCode:null,closeReason:null,lastEvent:'CONNECTING'};console.log('Binance WebSocket: CONNECTING');this.onUpdate(this);const base=process.env.BINANCE_WS_URL??'wss://stream.binance.com/ws';const url=`${base.replace(/\/$/,'')}/${this.streamSymbol}@depth@100ms`;this.ws=new WebSocket(url);this.ws.on('open',()=>{this.state='CONNECTED';this.diagnostic.error=null;this.log('Binance WebSocket: OPEN');this.log('Binance WebSocket: SUBSCRIBED');this.syncSnapshot().catch(e=>{this.fail(e);this.ws?.close();});});this.ws.on('message',r=>{if(!this.firstMessageLogged){this.firstMessageLogged=true;this.log('Binance WebSocket: FIRST MESSAGE RECEIVED');}this.receive(r.toString())});this.ws.on('error',e=>this.fail(e));this.ws.on('close',(code,reason)=>{this.ws=undefined;this.diagnostic.closeCode=code;this.diagnostic.closeReason=reason.toString();this.book.markDisconnected();this.state='DISCONNECTED';console.error(`Binance WebSocket: CLOSE\nError: ${this.diagnostic.error||'—'}\nClose code: ${code}\nClose reason: ${reason.toString()||'—'}\nReconnect attempt: ${this.reconnects+1}`);this.onUpdate(this);this.schedule()});}
 private async syncSnapshot(){this.state='SYNCING';this.onUpdate(this);const snapshotUrl=`https://api.binance.com/api/v3/depth?symbol=${this.streamSymbol.toUpperCase()}&limit=1000`;const r=await fetch(snapshotUrl);if(!r.ok)throw new Error(`order-book snapshot HTTP ${r.status} from ${snapshotUrl}`);const s=await r.json() as any;if(typeof s.lastUpdateId!=='number')throw new Error('order-book snapshot missing lastUpdateId');this.book.loadSnapshot(s.lastUpdateId,this.levels(s.bids),this.levels(s.asks),Date.now(),null);const queued=this.buffered;this.buffered=[];for(const d of queued)this.apply(d);this.state=this.book.status==='LIVE'?'LIVE':'SYNCING';this.onUpdate(this);}
 private receive(raw:string){let m:any;try{m=JSON.parse(raw)}catch(e){this.fail(new Error(`malformed Binance message: ${e instanceof Error?e.message:String(e)}`));return}if(typeof m?.U!=='number'||typeof m?.u!=='number'){this.fail(new Error(`unexpected Binance message format: ${raw.slice(0,240)}`));return}const d={firstUpdateId:m.U,finalUpdateId:m.u,bids:this.levels(m.b),asks:this.levels(m.a),exchangeTimestamp:typeof m.E==='number'?m.E:null};if(this.book.sequence===null){this.buffered.push(d);return}this.apply(d);}
 private apply(d:any){const wasLive=this.state==='LIVE';if(!this.book.apply(d)){this.state='RESYNCING';this.diagnostic.error=`sequence gap before update ${d.firstUpdateId}; local sequence ${this.book.sequence}`;console.error(`Binance order book: RESYNCING\nError: ${this.diagnostic.error}`);this.onUpdate(this);this.ws?.close();return}if(!wasLive){console.log('Binance order book: SYNCHRONIZED');this.diagnostic.lastEvent='ORDER_BOOK_SYNCHRONIZED';}this.state='LIVE';this.onUpdate(this);}
 private levels(xs:any[]):OrderBookLevel[]{return Array.isArray(xs)?xs.map(x=>({price:+x[0],quantity:+x[1]})).filter(x=>Number.isFinite(x.price)&&x.price>0&&Number.isFinite(x.quantity)&&x.quantity>=0):[];}
 private schedule(){if(this.stopped||this.timer)return;this.reconnects++;this.diagnostic.reconnectAttempt=this.reconnects;this.timer=setTimeout(()=>{this.timer=undefined;this.connect()},Math.min(30000,1000*Math.max(1,this.reconnects)));}
 stop(){this.stopped=true;if(this.timer)clearTimeout(this.timer);this.ws?.close();this.ws=undefined;}
 get snapshot(){return this.book.snapshot;} get status(){return this.state;} get reconnectCount(){return this.reconnects;} get sequenceStatus(){return this.book.sequence===null?'UNKNOWN':this.book.status==='LIVE'?'VALID':this.book.status;} get connectionDiagnostic(){return {...this.diagnostic};}
 getSnapshot():NormalizedOrderBook{return this.snapshot;} getStatus():AdapterStatus{return this.status;} getDiagnostics():ConnectionDiagnostics{return this.connectionDiagnostic;} getReconnectCount(){return this.reconnectCount;} getSequenceStatus(){return this.sequenceStatus;}
}
