import WebSocket from 'ws';
import { LocalOrderBook } from './orderbook';
import type { AdapterStatus, ConnectionDiagnostics, ExchangeAdapter, NormalizedOrderBook, OrderBookLevel } from './types';

type BybitMessage={topic?:string;type?:'snapshot'|'delta';ts?:number;cts?:number;data?:{s?:string;b?:string[][];a?:string[][];u?:number;seq?:number};op?:string;success?:boolean;ret_msg?:string;retCode?:number};
export class BybitAdapter implements ExchangeAdapter {
 readonly exchange='bybit'; readonly symbol='BTC/USDT'; private ws?:WebSocket; private timer?:NodeJS.Timeout; private heartbeat?:NodeJS.Timeout; private stopped=false; private reconnects=0; private state:AdapterStatus='STARTING'; private book=new LocalOrderBook(this.exchange,this.symbol); private diagnostics:ConnectionDiagnostics={error:null,closeCode:null,closeReason:null,reconnectAttempt:0,lastEvent:null}; private topic:string;
 constructor(private onUpdate:(adapter:BybitAdapter)=>void=()=>{},private streamSymbol='BTCUSDT'){this.topic=`orderbook.${process.env.BYBIT_ORDERBOOK_DEPTH??'200'}.${streamSymbol}`;}
 start(){this.stopped=false;this.connect();}
 private update(message?:string){if(message){this.diagnostics.lastEvent=message;console.log(message);}this.onUpdate(this);}
 private fail(error:unknown){this.diagnostics.error=error instanceof Error?error.message:String(error);this.state='ERROR';console.error(`Bybit WebSocket: ERROR\nError: ${this.diagnostics.error}\nClose code: ${this.diagnostics.closeCode??'—'}\nClose reason: ${this.diagnostics.closeReason||'—'}\nReconnect attempt: ${this.reconnects+1}`);this.onUpdate(this);}
 private connect(){if(this.stopped||this.ws)return;this.state='STARTING';this.book.markResyncing();this.diagnostics={...this.diagnostics,closeCode:null,closeReason:null,lastEvent:'CONNECTING'};this.update('Bybit WebSocket: CONNECTING');this.ws=new WebSocket(process.env.BYBIT_WS_URL??'wss://stream.bybit.com/v5/public/spot');this.ws.on('open',()=>{this.state='CONNECTED';this.update('Bybit WebSocket: OPEN');this.ws?.send(JSON.stringify({op:'subscribe',args:[this.topic]}));this.heartbeat=setInterval(()=>{if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify({op:'ping'}));},20_000);});this.ws.on('message',raw=>this.receive(raw.toString()));this.ws.on('error',e=>this.fail(e));this.ws.on('close',(code,reason)=>{this.ws=undefined;if(this.heartbeat)clearInterval(this.heartbeat);this.heartbeat=undefined;this.book.markDisconnected();this.state='DISCONNECTED';this.diagnostics.closeCode=code;this.diagnostics.closeReason=reason.toString();this.onUpdate(this);this.schedule();});}
 receiveForTest(raw:string){this.receive(raw);}
 private receive(raw:string){let m:BybitMessage;try{m=JSON.parse(raw)}catch(e){this.fail(new Error(`malformed Bybit message: ${e instanceof Error?e.message:String(e)}`));return;}if(m.op==='ping')return;if(m.op==='subscribe'){if(m.success){this.update('Bybit WebSocket: SUBSCRIBED');return;}this.fail(new Error(m.ret_msg??`subscription rejected (${m.retCode??'unknown'})`));return;}if(m.topic!==this.topic||!m.data)return;const d=m.data;if(typeof d.u!=='number'||!Array.isArray(d.b)||!Array.isArray(d.a)){this.fail(new Error('invalid Bybit order-book message'));return;}const bids=this.levels(d.b),asks=this.levels(d.a),received=Date.now(),exchangeTime=typeof m.cts==='number'?m.cts:typeof m.ts==='number'?m.ts:null;
  if(m.type==='snapshot'){this.book.loadSnapshot(d.u,bids,asks,received,exchangeTime);this.book.markLive();this.state='LIVE';this.diagnostics.error=null;this.update('Bybit order book: SYNCHRONIZED');return;}
  if(m.type!=='delta'){this.fail(new Error(`unsupported Bybit order-book type: ${String(m.type)}`));return;}if(this.book.sequence===null){this.state='RESYNCING';this.ws?.close();return;}if(d.u<=Number(this.book.sequence))return;if(!this.book.apply({firstUpdateId:d.u,finalUpdateId:d.u,bids,asks,exchangeTimestamp:exchangeTime},received)){this.state='RESYNCING';this.diagnostics.error=`Bybit update sequence invalid (u=${d.u}, local=${this.book.sequence})`;this.onUpdate(this);this.ws?.close();}else this.onUpdate(this);}
 private levels(rows:string[][]):OrderBookLevel[]{return rows.map(([p,q])=>({price:Number(p),quantity:Number(q)})).filter(x=>Number.isFinite(x.price)&&x.price>0&&Number.isFinite(x.quantity)&&x.quantity>=0);}
 private schedule(){if(this.stopped||this.timer)return;this.reconnects++;this.diagnostics.reconnectAttempt=this.reconnects;this.timer=setTimeout(()=>{this.timer=undefined;this.connect();},Math.min(30_000,1000*this.reconnects));}
 stop(){this.stopped=true;if(this.timer)clearTimeout(this.timer);if(this.heartbeat)clearInterval(this.heartbeat);this.timer=undefined;this.heartbeat=undefined;this.ws?.close();this.ws=undefined;}
 getSnapshot():NormalizedOrderBook{return this.book.snapshot;}getStatus(){return this.state;}getDiagnostics(){return {...this.diagnostics};}getReconnectCount(){return this.reconnects;}getSequenceStatus(){return this.book.sequence===null?'UNKNOWN':this.book.status==='LIVE'?'VALID':this.book.status;}
}
