import { createServer } from 'node:http';
import { BinanceAdapter } from './binance';
import { BybitAdapter } from './bybit';
import { evaluateBothDirections } from './arbitrage';
import { feeSchedules } from './fees';
import { dataAgeMs, freshness } from './orderbook';
import type { ExchangeAdapter } from './types';

const clients=new Set<import('node:http').ServerResponse>();
const adapters:ExchangeAdapter[]=[];
let latest:any={scannerStatus:'STARTING',exchange:'multiple',symbol:'BTC/USDT',bookStatus:'SYNCING',reconnects:0,sequenceStatus:'UNKNOWN',exchangeTimestamp:null,receivedTimestamp:null,processedTimestamp:null,dataAgeMs:null,processingLatencyMs:null,bestBid:null,bestAsk:null,bidSize:null,askSize:null,spread:null,crossExchangeOpportunities:0,connectionError:null,closeCode:null,closeReason:null,reconnectAttempt:0,lastEvent:null,exchanges:{},evaluations:{},opportunities:[],feeAssumptions:{binance:feeSchedules.binance,bybit:feeSchedules.bybit}};
let publishTimer:NodeJS.Timeout|undefined;
const changed=()=>{if(publishTimer)return;publishTimer=setTimeout(()=>{publishTimer=undefined;publish();},20);};
const binance=new BinanceAdapter('btcusdt',changed);
const bybit=new BybitAdapter(changed,'BTCUSDT');
adapters.push(binance,bybit);
function market(adapter:ExchangeAdapter){const book=adapter.getSnapshot(),status=adapter.getStatus(),age=dataAgeMs(book);return {book,connectionStatus:status,sequenceValid:adapter.getSequenceStatus()==='VALID',telemetry:{exchange:adapter.exchange,symbol:adapter.symbol,status,bookStatus:status==='LIVE'?'SYNCHRONIZED':status,sequenceStatus:adapter.getSequenceStatus(),reconnects:adapter.getReconnectCount(),...adapter.getDiagnostics(),exchangeTimestamp:book.exchangeTimestamp,receivedTimestamp:book.receivedTimestamp||null,processedTimestamp:book.processedTimestamp||null,dataAgeMs:age,freshness:freshness(age),processingLatencyMs:book.receivedTimestamp?book.processedTimestamp-book.receivedTimestamp:null,bestBid:status==='LIVE'?book.bids[0]?.price??null:null,bestAsk:status==='LIVE'?book.asks[0]?.price??null:null,bidSize:status==='LIVE'?book.bids[0]?.quantity??null:null,askSize:status==='LIVE'?book.asks[0]?.quantity??null:null,sequence:book.sequence}};}
function evaluate(){const a=market(binance),b=market(bybit),result=evaluateBothDirections(a,b,feeSchedules,Number(process.env.ARB_REFERENCE_QUANTITY??0.01),Date.now(),Number(process.env.MAX_BOOK_AGE_MS??2000));return {a,b,result};}
function publish(){const {a,b,result}=evaluate(),valid=[result.aToB.opportunity,result.bToA.opportunity].filter(o=>o?.valid);latest={...latest,scannerStatus:a.telemetry.status==='LIVE'&&b.telemetry.status==='LIVE'?'LIVE':'DEGRADED',bookStatus:a.telemetry.bookStatus==='SYNCHRONIZED'&&b.telemetry.bookStatus==='SYNCHRONIZED'?'SYNCHRONIZED':'PARTIAL',reconnects:a.telemetry.reconnects+b.telemetry.reconnects,sequenceStatus:`Binance:${a.telemetry.sequenceStatus};Bybit:${b.telemetry.sequenceStatus}`,exchangeTimestamp:null,receivedTimestamp:null,processedTimestamp:Date.now(),dataAgeMs:null,processingLatencyMs:null,bestBid:null,bestAsk:null,bidSize:null,askSize:null,spread:null,crossExchangeOpportunities:valid.length,connectionError:[a.telemetry.error&&`binance: ${a.telemetry.error}`,b.telemetry.error&&`bybit: ${b.telemetry.error}`].filter(Boolean).join(' | ')||null,exchanges:{binance:a.telemetry,bybit:b.telemetry},evaluations:{binanceToBybit:result.aToB,bybitToBinance:result.bToA},opportunities:valid,feeAssumptions:{binance:feeSchedules.binance,bybit:feeSchedules.bybit}};const msg=`data: ${JSON.stringify(latest)}\n\n`;for(const c of clients)c.write(msg);}
const server=createServer((req,res)=>{if(req.url==='/health'||req.url==='/telemetry'){res.writeHead(200,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(latest));return;}if(req.url==='/events'){res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive','access-control-allow-origin':'*'});res.write(`data: ${JSON.stringify(latest)}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return;}res.writeHead(404);res.end();});
server.listen(Number(process.env.SCANNER_PORT??4000),()=>{console.log('Crypto Arbitrage Scanner\n------------------------\nScanner: RUNNING\nMarkets: Binance + Bybit BTC/USDT\nTelemetry: http://localhost:'+Number(process.env.SCANNER_PORT??4000)+'/telemetry');binance.start();bybit.start();changed();});
let shuttingDown=false;const shutdown=(signal:string)=>{if(shuttingDown)return;shuttingDown=true;console.log(`Scanner: shutting down (${signal})`);for(const adapter of adapters)adapter.stop();if(publishTimer)clearTimeout(publishTimer);for(const c of clients)c.end();clients.clear();server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),2000).unref();};process.on('SIGINT',()=>shutdown('SIGINT'));process.on('SIGTERM',()=>shutdown('SIGTERM'));
